name: osu-sunset
services:
  next-frontend:
    build: .
    ports:
      - "3090:3000"
    restart: always
    networks:
      - default

networks:
  default:
    external: true
    name: sunrise-network
